name: Bug report
description: Create a report to help us improve & fix bugs
title: "[BUG] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Briefly describe the bug.
      placeholder: Describe the bug
      value:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **To Reproduce**
        Steps to reproduce the behaviour:
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the bug.
      placeholder: "1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See error"
      value:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Expected behaviour**
        A clear and concise description of what you expected to happen.
  - type: textarea
    id: expected
    attributes:
      label: Expected Outcome
      description: Describe what you expected to happen.
      placeholder: Describe the expected behaviour
      value:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Screenshots**
        If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain your problem.
      placeholder: Add screenshots
      value:
  - type: markdown
    attributes:
      value: |
        **Additional context**
        Add any other relevant information or context about the problem here.
  - type: textarea
    id: context
    attributes:
      label: Extra Information
      description: Include any additional details about the problem.
      placeholder: Add any other context
      value: