name: Feature request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        **Is your feature request related to a problem? Please describe.**  
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: A clear and concise description of what the problem is.
      placeholder: Describe the problem
      value:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Describe the solution you'd like**  
        A clear and concise description of what you want to happen.
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: A clear and concise description of what you want to happen.
      placeholder: Describe the solution
      value:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Describe alternatives you've considered**  
        A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Describe the alternatives
      value:
  - type: markdown
    attributes:
      value: |
        **Additional context**  
        Add any other context or screenshots about the feature request here.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Add any other context
      value: