name: Feature request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: [suggestion]
body:
  - type: markdown
    attributes:
      value: |
        **Is your feature request related to a problem? Please describe.**
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Summarize the problem briefly.
      placeholder: Describe the problem
      value:
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        **Describe the feature you'd like**
        A clear and concise description of what you want to happen.
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Summarize the feature briefly.
      placeholder: Describe the solution
      value:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Additional context**
        Add any other context or screenshots about the feature request here.
  - type: textarea
    id: context
    attributes:
      label: Extra Information or background
      description: Include any additional details or screenshots related to the feature request here (such as mock designs or examples of the feature).
      placeholder: Add any other things you think we should know
      value:
