name: Help wanted
description: Request help with a problem or question
title: "[HELP] "
labels: [help wanted]
body:
  - type: markdown
    attributes:
      value: |
        **Describe the issue**
        A clear and concise description of what you need help with.
  - type: textarea
    id: issue
    attributes:
      label: Issue Summary
      description: Briefly describe the issue.
      placeholder: Describe the issue
      value:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Steps to reproduce**
        Steps to reproduce the issue:
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the issue.
      placeholder: "1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See issue"
      value:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Expected outcome**
        A clear and concise description of what you expected to happen.
  - type: textarea
    id: expected
    attributes:
      label: Expected Outcome
      description: Describe what you expected to happen.
      placeholder: Describe the expected outcome
      value:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Screenshots**
        If applicable, add screenshots or mylog.log to help explain your issue.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or files
      description: Add screenshots to help explain your issue. You should also add the mylog.log file if available.
      placeholder: Add screenshots, or mylog.log
      value:
  - type: markdown
    attributes:
      value: |
        **Additional context**
        Add any other relevant information or context about the issue here.
  - type: textarea
    id: context
    attributes:
      label: Extra Information
      description: Include any additional details about the issue.
      placeholder: Add any other context
      value:
