name: Security vulnerability
description: Report a security vulnerability
title: "[SECURITY] "
labels: [security]
body:
  - type: markdown
    attributes:
      value: |
        **Describe the vulnerability**
        A clear and concise description of the security vulnerability.
  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Briefly describe the vulnerability.
      placeholder: Describe the vulnerability
      value:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Steps to reproduce**
        Steps to reproduce the vulnerability:
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the vulnerability.
      placeholder: "1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See vulnerability"
      value:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Expected outcome**
        A clear and concise description of what you expected to happen.
  - type: textarea
    id: expected
    attributes:
      label: Expected Outcome
      description: Describe what you expected to happen.
      placeholder: Describe the expected outcome
      value:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Screenshots**
        If applicable, add screenshots to help explain the vulnerability.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain the vulnerability.
      placeholder: Add screenshots
      value:
  - type: markdown
    attributes:
      value: |
        **Additional context**
        Add any other relevant information or context about the vulnerability here.
  - type: textarea
    id: context
    attributes:
      label: Extra Information
      description: Include any additional details about the vulnerability.
      placeholder: Add any other context
      value: