name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write
  actions: read    # required by deploy-pages@v4

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4                      # updated to v4 :contentReference[oaicite:5]{index=5}

      - name: Setup Node.js
        uses: actions/setup-node@v4                   # updated to v4 :contentReference[oaicite:6]{index=6}
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: website
        run: npm ci

      - name: Build site
        working-directory: website
        run: npm run build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5               # updated to v5 :contentReference[oaicite:7]{index=7}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3        # updated to v3 :contentReference[oaicite:8]{index=8}
        with:
          path: website/build

      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4                 # updated to v4 :contentReference[oaicite:9]{index=9}
