name: Automatic Semantic Versioning

on: [push, pull_request]

jobs:
  semantic_version:
    runs-on: ubuntu-latest
    steps:
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.4.0
      with:
        bump_each_commit_patch_pattern: ''
