name: Update Stats

on:
  push:
    branches: [main]  # Or 'gh-pages' if you're using that
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo with full history
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate repo stats
      run: |
        mkdir -p website/stats

        # Get contributors via GitHub API
        curl -s https://api.github.com/repos/${{ github.repository }}/contributors > contributors.json

        # Get commit count from full git history
        commit_count=$(git rev-list --count HEAD)

        # Extract needed contributor info
        contributors=$(jq 'map({login, html_url, avatar_url, contributions})' contributors.json)

        # Create the stats JSON
        jq -n --argjson contributors "$contributors" --argjson commits "$commit_count" \
          '{contributors: $contributors, commit_count: $commits}' > website/stats/stats.json

    - name: Commit changes to new branch and open PR
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "Akaalroop Singh (GitHub Actions)"
        git config user.email "spacexplorer11@proton.me"

        # Create a temporary branch
        BRANCH_NAME="update-stats-$(date +%s)"
        git checkout -b "$BRANCH_NAME"

        # Commit the stats file
        git add website/stats/stats.json
        git commit -m "Update stats.json (via GitHub Actions)"

        # Push to the new branch using the PAT
        git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git "$BRANCH_NAME"

        # Install GitHub CLI and create a PR
        sudo apt-get install -y gh
        echo "${GH_PAT}" | gh auth login --with-token
        gh pr create --title "Update stats.json" --body "Automated update from GitHub Actions" --base main --head "$BRANCH_NAME"

        # Approve, merge, and delete the branch
        PR_URL=$(gh pr view "$BRANCH_NAME" --json url -q .url)
        gh pr merge "$PR_URL" --squash --delete-branch --admin