name: Update Stats

on:
  push:
    branches: [main]  # Or 'gh-pages' if you're using that
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo with full history
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate repo stats
      run: |
        mkdir -p website/stats

        # Get contributors via GitHub API
        curl -s https://api.github.com/repos/${{ github.repository }}/contributors > contributors.json

        # Get commit count from full git history
        commit_count=$(git rev-list --count HEAD)

        # Extract needed contributor info
        contributors=$(jq 'map({login, html_url, avatar_url, contributions})' contributors.json)

        # Create the stats JSON
        jq -n --argjson contributors "$contributors" --argjson commits "$commit_count" \
          '{contributors: $contributors, commit_count: $commits}' > website/stats/stats.json

    - name: Commit and push updated stats.json
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add website/stats/stats.json
        git commit -m "Update stats.json" || echo "No changes to commit"
        git push